import { useContext, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FaGraduationCap, FaCode, FaTrophy, FaBookReader } from "react-icons/fa";

import Login from "../components/auth/Login";
import Signup from "../components/auth/Signup";

import { AuthContext } from "../context/AuthContext";
import * as authService from "../api/authService";

import "../css/auth.css";

export default function Auth() {
    const [loginMode, setLoginMode] = useState(true);
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();
    const { setUser } = useContext(AuthContext);

    const login = async (data) => {
        setLoading(true);
        try {
            const response = await authService.login(data);
            const authData = response?.data?.data;
            const token = authData?.token;
            const userData = authData?.user || authData;
            if (token) {
                localStorage.setItem("token", token);
            }
            setUser(userData);
            navigate("/dashboard", { replace: true });
        } finally {
            setLoading(false);
        }
    };

    const signup = async (fd) => {
        setLoading(true);
        try {
            const response = await authService.signup(fd);
            const authData = response?.data?.data;
            const token = authData?.token;
            const userData = authData?.user || authData;
            if (token) {
                localStorage.setItem("token", token);
                setUser(userData);
                navigate("/dashboard", { replace: true });
            } else {
                setLoginMode(true);
            }
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="auth-page">
            {/* LEFT — hero with background image generated by AI */}
            <aside className="auth-hero">
                <div className="auth-brand">
                    <div className="auth-brand-mark">
                        <FaGraduationCap />
                    </div>
                    <span>Momentum Learning</span>
                </div>

                <div className="auth-hero-text">
                    <h1>Structured momentum for lifelong learners.</h1>
                    <p>
                        Organize your knowledge, track your progress, and stay
                        consistent. A dashboard designed for professional
                        growth — one topic, one problem, at a time.
                    </p>

                    <div className="auth-hero-features">
                        <div className="hero-feature">
                            <div className="hero-feature-icon">
                                <FaBookReader size={16} />
                            </div>
                            <h5>Topic Planner</h5>
                            <span>Break down subjects into sub-topics with deadlines.</span>
                        </div>
                        <div className="hero-feature">
                            <div className="hero-feature-icon">
                                <FaCode size={16} />
                            </div>
                            <h5>LeetCode Streak</h5>
                            <span>Log your daily problem with screenshots and notes.</span>
                        </div>
                        <div className="hero-feature">
                            <div className="hero-feature-icon">
                                <FaTrophy size={16} />
                            </div>
                            <h5>Progress History</h5>
                            <span>Visualize your completed work and revisit notes.</span>
                        </div>
                    </div>
                </div>

                <div className="auth-hero-footer">
                    © {new Date().getFullYear()} Momentum Learning · Built for consistency.
                </div>
            </aside>

            {/* RIGHT — auth form */}
            <section className="auth-panel">
                <div className="auth-card">
                    <div className="auth-tabs" role="tablist">
                        <button
                            role="tab"
                            aria-selected={loginMode}
                            className={`auth-tab ${loginMode ? "active" : ""}`}
                            onClick={() => setLoginMode(true)}
                            disabled={loading}
                        >
                            Log In
                        </button>
                        <button
                            role="tab"
                            aria-selected={!loginMode}
                            className={`auth-tab ${!loginMode ? "active" : ""}`}
                            onClick={() => setLoginMode(false)}
                            disabled={loading}
                        >
                            Sign Up
                        </button>
                    </div>

                    {loginMode ? (
                        <Login onLogin={login} loading={loading} />
                    ) : (
                        <Signup onSignup={signup} loading={loading} />
                    )}

                    <div className="auth-switch">
                        {loginMode ? (
                            <>
                                Don't have an account?
                                <button onClick={() => setLoginMode(false)} disabled={loading}>
                                    Sign up
                                </button>
                            </>
                        ) : (
                            <>
                                Already have an account?
                                <button onClick={() => setLoginMode(true)} disabled={loading}>
                                    Log in
                                </button>
                            </>
                        )}
                    </div>
                </div>
            </section>
        </div>
    );
}
